%types = (
    'TV Series'   => 0,
    'OVA'         => 1,
    'Movie'       => 2,
    'TV Special'  => 3,
    'Web'         => 4,
    'Music Video' => 5,
    'unknown'     => 6,
    'Other'       => 7
);

# Hash for title types
%title_types = ( 'main' => 0, 'synonym' => 1, 'official' => 2, 'short' => 3 );

# language codes list
# https://anidb.net/perl-bin/animedb.pl?show=dump&t=lang
%languages = (
    'x-unk'    => 1,
    'ja'       => 2,
    'zh'       => 3,
    'en'       => 4,
    'de'       => 5,
    'fr'       => 6,
    'it'       => 7,
    'es'       => 8,
    'ru'       => 9,
    'ko'       => 10,
    'pl'       => 11,
    'sv'       => 12,
    'ar'       => 13,
    'pt'       => 14,
    'no'       => 15,
    'pt-BR'    => 16,
    'ca'       => 17,
    'cs'       => 18,
    'da'       => 19,
    'nl'       => 20,
    'fi'       => 21,
    'el'       => 22,
    'he'       => 23,
    'hu'       => 24,
    'x-in'     => 25,
    'lt'       => 26,
    'th'       => 27,
    'tr'       => 28,
    'zh-x-cmn' => 29,
    'zh-x-yue' => 30,
    'zh-x-nan' => 31,
    'x-other'  => 32,
    'ro'       => 33,
    'my'       => 34,
    'sk'       => 35,
    'sl'       => 36,
    'tt'       => 37,
    'lv'       => 38,
    'ka'       => 39,
    'la'       => 40,
    'vi'       => 41,
    'id'       => 42,
    'ta'       => 43,
    'bg'       => 44,
    'x-jat'    => 45,
    'et'       => 46,
    'uk'       => 47,
    'hr'       => 48,
    'sr'       => 49,
    'zh-Hant'  => 50,
    'zh-Hans'  => 51,
    'is'       => 52,
    'al'       => 53,
    'bd'       => 54,
    'x-kot'    => 55,
    'es-LA'    => 56,
    'gl'       => 57,
    'jv'       => 58,
    'fa'       => 59,
    'tl'       => 60,
    'ht'       => 61,
    'mn'       => 62,
    'x-zht'    => 63,
    'hi'       => 64,
    'si'       => 65,
    'eo'       => 66,
    'ur'       => 67,
    'eu'       => 68,
    'af'       => 69,
    'grc'      => 70,
    'ne'       => 71,
    'bs'       => 72,
    'tl'       => 73,
    'x-tht'    => 74
);

1;
